# Generated by Django 5.1.2 on 2024-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='thumbnail',
            field=models.TextField(default='https://www.myutilitygenius.co.uk/assets/images/blogs/default-image.jpg'),
            preserve_default=False,
        ),
    ]
