# Generated by Django 5.1.2 on 2024-10-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_coursematerial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='likes',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='thumbnail',
            field=models.TextField(default='https://www.myutilitygenius.co.uk/assets/images/blogs/default-image.jpg'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='course_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.coursematerial'),
        ),
    ]
