# Generated by Django 5.1.2 on 2024-11-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_liked_videos_alter_coursematerial_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
