# Generated by Django 5.1.2 on 2024-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='saved_by',
            field=models.ManyToManyField(related_name='courses_saved', to='base.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course_images/default.jpg', upload_to='course_images'),
        ),
    ]
